
version: 2.1

jobs:
  compile_exec:
  machine:
      image: ubuntu-2004:202010-01
   
    steps:
      - checkout
      - run:ls
      - run:pwd
      - run:ip addr show
      
workflows:
  compile_exec:
    jobs:
      - compile_exec
